name = "FormalisingMathematics2025"
defaultTargets = ["FormalisingMathematics2025"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
linter.style.longLine = true
linter.unusedTactic = false
linter.unusedVariables = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"

[[lean_lib]]
name = "FormalisingMathematics2025"
